### ISSUE TITLE
Hitsound Selector in Noteskin Selector (this one)

### ISSUE THREAD

**Issue by UltraFatBoi** [Meme1079/NoteSkin-Selector-Remaster#1]
### What feature you wanted to see in this project

This feature was from the old version of the Noteskin Selector (i think) and I would like to have this feature re-added. (you don't have to if you don't want to)

Here is how it would work:
- Hitsounds would be placed in "NoteSkin Selector Remastered/sounds/hitsounds
- You could change the volume of the hitsound(s)
- The built-in hitsounds would be: Default, Dave and Bambi, Slap, Crunch, and Pizza Tower Taunt

(also the notesplash selector doesn't work)

**Comment by MemeFlavor** [comment]
This one is a maybe, also the reason why the notesplash selector doesn't work currently. Because I haven't implemented the code yet, that will be in update `2.0.0`. Thanks for the suggestion.
